const starshipActionTypes = {
  FETCH_STARSHIP_LIST_START: 'FETCH_STARSHIP_LIST_START',
  FETCH_STARSHIP_LIST_SUCCESS: 'FETCH_STARSHIP_LIST_SUCCESS',
  FETCH_STARSHIP_LIST_FAILURE: 'FETCH_STARSHIP_LIST_FAILURE',
};

export default starshipActionTypes;