const starshipActionTypes = {
  FETCH_STARSHIP_LIST_START: 'FETCH_STARSHIP_LIST_START',
  FETCH_STARSHIP_LIST_SUCCESS: 'FETCH_STARSHIP_LIST_SUCCESS',
  FETCH_STARSHIP_LIST_FAILURE: 'FETCH_STARSHIP_LIST_FAILURE',

  ADD_STARSHIP_IN_FLEET: 'ADD_STARSHIP_IN_FLEET',
  REMOVE_STARSHIP_FROM_FLEET: 'REMOVE_STARSHIP_FROM_FLEET',
};

export default starshipActionTypes;